var pics=[];var nav_boxes=[];var bgs=[];var nav_config={"home":{index:1,top:-73,left:500,width:100,height:143,rotate:-60,image:'home.png',bg:'bg1_opt.jpg',href:'home_page',hashAddress:'home'},"spotlight":{index:2,top:-53,left:480,width:100,height:143,rotate:-70,image:'spotlight.png',bg:'bg2_opt.jpg',href:'spotlight_page',hashAddress:'spotlight'},proshows:{index:3,top:-28,left:465,width:100,height:143,rotate:-80,image:'proshows.png',bg:'bg3_opt.jpg',href:'proshows_page',hashAddress:'proshows'},events:{index:4,top:-3,left:455,width:100,height:143,rotate:-90,image:'events.png',bg:'bg4_opt.jpg',href:'events_page',hashAddress:'events'},hospitality:{index:5,top:22,left:455,width:100,height:143,rotate:-100,image:'hospitality.png',bg:'bg5_opt.jpg',href:'hospitality_page',hashAddress:'hospitality'},eunoia:{index:7,top:66,left:470,width:100,height:143,rotate:-115,image:'eunoia.png',bg:'bg4_opt.jpg',href:'eunoia_page',hashAddress:'eunoia'},wcs:{index:6,top:42,left:460,width:100,height:143,rotate:-108,image:'wcs.png',bg:'bg3_opt.jpg',href:'wcs_page',hashAddress:'wcs'}}
function navBoxes(domParent,id){this.load=function(domParent,id){this.config=nav_config[id];this.id=id;this.hashAddress=this.config.hashAddress;hashes[this.hashAddress]=this;this.index=this.config.index;this.status=0;this.domParent=domParent;this.domParent.append("<div id='"+this.id+"'></div>");this.jQSelector=$("#"+this.id);this.angle=this.config.rotate;this.bg="url('images/"+this.config.image+"')";this.link=this.config.href;this.pageBg=$("<div></div>").appendTo($("body"));this.pageBgSrc="url('images/"+this.config.bg+"')";this.pageBg.css({backgroundImage:this.pageBgSrc,backgroundSize:"100% 100%",backgroundRepeat:"no-repeat",zIndex:-this.index-20,position:"absolute",width:"100%",height:"100%",left:0,top:"-100%"});this.size={width:this.config.width,height:this.config.height};this.coords={top:this.config.top,left:this.config.left};this.jQSelector.css({position:"absolute",width:this.size.width,height:this.size.height,left:this.coords.left,top:this.coords.top,zIndex:100-this.index,backgroundImage:this.bg,backgroundSize:"100% 100%",cursor:"pointer",'transition':'transform .3s','-moz-transition':'-moz-transform .3s','-webkit-transition':'-webkit-transform .3s','-o-transition':'-o-transform .3s'});this.rotate(this.angle);this.attachHandlers();this.resize();};this.flyToContainer=function(){this.detachHandlers();this.rotate(0);this.status=1;this.holderLeft=pics[0].coords.left+pics[0].size.width/2.0-this.size.width/2.0;this.holderTop=pics[0].coords.top+pics[0].size.height/2.0-this.size.height/2.0;this.jQSelector.stop().animate({top:this.holderTop,left:this.holderLeft},1500,'easeInOutExpo');for(var i=0;i<nav_boxes.length;i++){if(nav_boxes[i].status&&this.id!=nav_boxes[i].id)
{nav_boxes[i].flyFromContainer();}}}
this.flyFromContainer=function(){this.attachHandlers();this.rotate(this.angle);this.jQSelector.stop().animate({top:this.coords.top,left:this.coords.left},300);this.status=0;}
this.followLink=function()
{document.location='#!/'+this.hashAddress}
this.click=function()
{$('#main_wrapper').stop().delay(0).animate({scrollLeft:$('#'+this.id+'_page').offset().left+$('#main_wrapper').scrollLeft()},1500,'easeInOutExpo');this.flyToContainer();if(Math.abs($('#'+this.id+'_page').offset().left)>1)
this.pageBg.css({top:"100%",left:"50%",width:"0%",height:"0%",opacity:0});this.pageBg.stop().delay(00).animate({top:"0%",left:"0%",width:"100%",height:"100%",opacity:1},{duration:1500,easing:"easeInOutExpo"});if(Math.abs($('#'+this.id+'_page').offset().left)>1)
for(var i=0;i<nav_boxes.length;i++)
{if(nav_boxes[i].index!=this.index)
{nav_boxes[i].pageBg.stop().delay(00).animate({top:"-100%"},{duration:1500,easing:"easeInOutExpo",complete:function(){$(this).css({opacity:0});}});}}}
this.showPresence=function(){this.jQSelector.stop().animate({left:this.coords.left-10,top:this.coords.top+10},300);}
this.hidePresence=function(){this.jQSelector.stop().animate({left:this.coords.left,top:this.coords.top},300);}
this.attachHandlers=function(){this.jQSelector.bind("mouseenter",{self:this},function(e){e.data.self.showPresence();});this.jQSelector.bind("mouseleave",{self:this},function(e){e.data.self.hidePresence();});this.jQSelector.bind("click",{self:this},function(e){e.data.self.followLink();});}
this.detachHandlers=function(){this.jQSelector.unbind("click");this.jQSelector.unbind("mouseenter");this.jQSelector.unbind("mouseleave");}
this.rotate=function(deg){this.jQSelector.css({"-webkit-transform":"rotate("+deg+"deg)","-moz-transform":"rotate("+deg+"deg)","-ms-transform":"rotate("+deg+"deg)","-o-transform":"rotate("+deg+"deg)"});}
this.resize=function(){var WIDTH=window.innerWidth,HEIGHT=window.innerHeight;var width=this.coords.width,height=this.coords.height;var W=WIDTH/1366.0,H=HEIGHT/768.0;var D=Math.sqrt(WIDTH*WIDTH+HEIGHT*HEIGHT)/Math.sqrt(1366*1366+768*768);if(this.status==0)
{this.size.width=this.config.width*D;this.size.height=this.config.height*D;this.coords.left=this.config.left*W;this.coords.top=this.config.top*H;this.jQSelector.css({left:this.coords.left,top:this.coords.top});}
else
{this.size.width=this.config.width*D;this.size.height=this.config.height*D;this.coords.left=this.config.left*W;this.coords.top=this.config.top*H;this.holderLeft=pics[0].coords.left+pics[0].size.width/2.0-this.size.width/2.0;this.holderTop=pics[0].coords.top+pics[0].size.height/2.0-this.size.height/2.0;this.jQSelector.css({left:this.holderLeft,top:this.holderTop});}
this.jQSelector.css({width:this.size.width,height:this.size.height});}
this.load(domParent,id);}
function nav_load()
{var domParent=$("#cards");for(var Id in nav_config)
{var nav=new navBoxes(domParent,Id);nav_boxes.push(nav);}
$("#main_wrapper").scroll(function(e){for(var i=0;i<bgs.length;i++)
{bgs[i].scroll();}});}
function BG(id)
{this.load=function(id){this.id=id;this.domParent=$("body");;this.scale=1.0;this.jQSelector=$("<div></div>").appendTo(this.domParent);this.bg="url('images/bg"+(this.id+1)+".jpg')";this.size={width:window.innerWidth,height:window.innerHeight};this.coords={top:0,left:0};this.jQSelector.css({position:"absolute",width:this.size.width,height:this.size.height,left:this.coords.left,top:this.coords.top,zIndex:-10+this.id,backgroundImage:this.bg,backgroundRepeat:"no-repeat",color:"#FFF",backgroundSize:"100% 100%"});this.scroll();this.resize();};this.resize=function(){var WIDTH=window.innerWidth,HEIGHT=window.innerHeight;this.jQSelector.css({width:window.innerWidth,height:window.innerHeight});this.scroll();};this.scroll=function(){var WIDTH=window.innerWidth,HEIGHT=window.innerHeight;this.scale=(WIDTH*this.id-$('#main_wrapper').scrollLeft())/(WIDTH);if(WIDTH*this.id<$('#main_wrapper').scrollLeft())
{this.bgPos="0px "+(HEIGHT*this.scale)+"px";this.jQSelector.css({backgroundPosition:this.bgPos,opacity:1});}
else
{this.bgPos="0px "+(HEIGHT*this.scale)+"px";this.jQSelector.css({backgroundPosition:"0 0",opacity:1-this.scale});}}
this.load(id);}